# Generated by Django 5.2.14 on 2026-05-20 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('founded_year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('rating', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_multiplayer', models.BooleanField(default=False)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('RPG', 'RPG'), ('Shooter', 'Shooter'), ('Strategy', 'Strategy')], max_length=20)),
                ('cover_image', models.ImageField(upload_to='game_covers/')),
                ('developer1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.developer')),
                ('platform', models.ManyToManyField(to='games.platform')),
            ],
        ),
        migrations.CreateModel(
            name='GameDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=100)),
                ('hours_to_complete', models.IntegerField()),
                ('steam_score', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
            ],
        ),
    ]
